### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/kamelmat-excusegenerator-2#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo @kamelmat ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Cuidado, tienes duplicadas estas importaciones en tu `app.js`
![Captura de pantalla de 2024-03-25 21-12-41](https://github.com/4GeeksAcademy/kamelmat-excusegenerator-2/assets/139759297/7a1034e4-71ce-491a-878b-035d84e490ee)
- En el `index.html` acuerdate de cambiar el `<title>` 
![Captura de pantalla de 2024-03-25 21-14-42](https://github.com/4GeeksAcademy/kamelmat-excusegenerator-2/assets/139759297/1d3b77b9-0ffc-477e-8566-276555ae2b4e)

**Comment by kamelmat** [comment]
### UPS!!!

Se me escapó lo del titulo y lo de copiar 2 veces en el app.js

Ya están corregidos!

🙏🏽 Gracias **EDO**

**Comment by EduardoHernandezGuzman** [comment]
Bien usado el `.map()`
